# Generated by Django 6.0.3 on 2026-04-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="webhook_event_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_event_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
