# Generated by Django 6.0.3 on 2026-04-01 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("shipping", "Shipping"), ("billing", "Billing")],
                        default="shipping",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("line_1", models.CharField(max_length=180)),
                ("line_2", models.CharField(blank=True, max_length=180)),
                ("city", models.CharField(max_length=90)),
                ("state", models.CharField(max_length=90)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="India", max_length=60)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
